site_name: gamache
site_description: "Fit GAMs to single-cell data"
site_url: https://lukasadam.github.io/gamache/
repo_url: https://github.com/lukasadam/gamache
repo_name: lukasadam/gamache
extra_css:
  - assets/stylesheets/extra.css

theme:
  name: material
  palette:
    primary: white
  logo: assets/images/gamache_logo.png
  language: en
  features:
    - tabs
    - instant
    - navigation.tabs
    - navigation.indexes
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocs-jupyter:
      execute: false        # RTD builds are resource-limited; keep execution off
      include_source: true  # show the notebook source link
      ignore_h1_titles: true
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            show_root_heading: true
            merge_init_into_class: true
            show_source: true
            show_signature: true
            separate_signature: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: api.md
  - Notebooks:
      - "Pseudotime testing": notebooks/01_Fit_GAM_to_trajectory.ipynb
